apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth0-deployment
  labels:
    app: auth0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: files-ms
  template:
    metadata:
      labels:
        app: files-ms
    spec:
      containers:
      - name: files-ms
        image: naqib/file_ms:latest
        ports:
        - containerPort: 5010
