apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
  labels:
    app: chat-service

spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-service

  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: naqib/chat-service:ver1.0
          ports:
            - containerPort: 5000
          env:
          - name: DB_URL
            valueFrom: 
              configMapKeyRef:
                name: redis-config
                key: redis-url
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service-service
spec:
  type: NodePort
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000
