apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ms-deployment
  labels:
    app: chat-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-ms
  template:
    metadata:
      labels:
        app: chat-ms
    spec:
      containers:
      - name: chat-ms
        image: naqib/chat_service:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu:  5m
            memory: 125Mi
          limits:
            cpu: 10m
            memory: 250Mi