apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: files-ms-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: files-ms-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
