apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: krakend-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: krakend-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
