apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50